require("preferences")
require("plugins")
require("keymaps")
require("lsp-config")
require("treesitter")
require("cmp-config")
require("gitsigns-config")
require("nvimtree-config")
require("lsp")
vim.cmd[[colorscheme gruvbox]]
